In [2]:
import numpy as np
import scipy.io as sio

### Load data from .mat file

In [48]:
mat_contents = sio.loadmat('ash85_data.mat') # ash219_data, ash85_data
data1 = mat_contents['x']
#print(data1)
#load the other matrix ash219_data'
#new_mat_contents=sio.loadmat('ash219_data.mat')
#print(new_mat_contents.items())
#data2=new_mat_contents['x']

### Print the format of the data: compressed sparse column format(csc)

In [49]:
print(data1)

  (0, 0)	1.0
  (1, 0)	1.0
  (5, 0)	1.0
  (6, 0)	1.0
  (7, 0)	1.0
  (0, 1)	1.0
  (1, 1)	1.0
  (2, 1)	1.0
  (7, 1)	1.0
  (8, 1)	1.0
  (9, 1)	1.0
  (1, 2)	1.0
  (2, 2)	1.0
  (3, 2)	1.0
  (9, 2)	1.0
  (2, 3)	1.0
  (3, 3)	1.0
  (4, 3)	1.0
  (9, 3)	1.0
  (10, 3)	1.0
  (11, 3)	1.0
  (3, 4)	1.0
  (4, 4)	1.0
  (11, 4)	1.0
  (22, 4)	1.0
  :	:
  (80, 79)	1.0
  (51, 80)	1.0
  (53, 80)	1.0
  (55, 80)	1.0
  (56, 80)	1.0
  (79, 80)	1.0
  (80, 80)	1.0
  (81, 80)	1.0
  (55, 81)	1.0
  (80, 81)	1.0
  (81, 81)	1.0
  (82, 81)	1.0
  (54, 82)	1.0
  (55, 82)	1.0
  (81, 82)	1.0
  (82, 82)	1.0
  (83, 82)	1.0
  (54, 83)	1.0
  (82, 83)	1.0
  (83, 83)	1.0
  (84, 83)	1.0
  (52, 84)	1.0
  (54, 84)	1.0
  (83, 84)	1.0
  (84, 84)	1.0


### Return a dense ndarray representation of this matrix.

In [50]:
A = data1.toarray() # or todense()
print(A.shape)
print(A)

(85, 85)
[[1. 1. 0. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 1. 0.]
 [0. 0. 0. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 1. 1.]]


In [51]:
from scipy.linalg import lu_factor, lu_solve
# Task 1: LU factorization
# define a right hand vector b with all ones
# use lu_factor and lu_solve to solve Ax=b for both inputs
# solve for both ash219_data, ash85_data
def create_matrix_b(rows_of_b):
    b=[]
    for i in range(rows_of_b):
        b.append(1)
    return b

output_vector=create_matrix_b(A.shape[1]) #Create an output vector based on the shape of the input vector
factored_matrix_A=lu_factor(A) #Factor the matrix into LU
print('The factored matrix is- ')
print(factored_matrix_A)
solution=lu_solve(factored_matrix_A,output_vector,trans=0)
print('The solution is-')
print(solution)


The factored matrix is- 
(array([[ 1.        ,  1.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  1.        ,  1.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 1.        ,  0.        ,  1.        , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  2.06666667,
         1.36342183,  1.43893805],
       [ 0.        ,  0.        ,  0.        , ...,  0.48387097,
         1.17213817, -0.67856123],
       [ 0.        ,  0.        ,  0.        , ..., -0.03225806,
        -0.61982465, -0.92815392]]), array([ 0,  2,  2,  3,  5,  5,  7,  7,  8,  9, 13, 13, 12, 21, 16, 15, 17,
       17, 19, 20, 20, 22, 46, 24, 24, 26, 26, 28, 38, 41, 42, 63, 62, 63,
       34, 65, 38, 64, 64, 48, 40, 49, 42, 51, 52, 64, 56, 48, 48, 49, 71,
       52, 59, 55, 59, 55, 64, 71, 69, 83, 72, 73, 63, 68, 65, 66, 67, 67,
       80, 80, 80, 78, 75, 74, 74, 76, 78, 77, 79, 79, 84, 8

In [52]:
# Task 2: verify the correctness of your solutions. 
# In the verification, you can use 
# numpy.allclose function that allows some tolerance
# verify the correctness of solutions for both ash219_data, ash85_data
#x=np.linalg.solve(A,output_vector) 
#print(x)
#if np.allclose(solution,x,atol=1.0):
#    print('Your solution is correct')
#else:
#    print('Your solution is wrong')
manual_output_vector=np.matmul(A,solution) #Generates the output_vector based on the solution obtained above. 
#Check if the components of the output vector generated above are within the tolerance limit
if np.allclose(manual_output_vector,output_vector,atol=1.0):
    print('Your solution is correct and all the elements are within the tolerance limit')
else:
    print('Your solution is wrong')
    

Your solution is correct
